// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: calculator.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Calculator_AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculator_AddRequest) Reset() {
	*x = Calculator_AddRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculator_AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculator_AddRequest) ProtoMessage() {}

func (x *Calculator_AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculator_AddRequest.ProtoReflect.Descriptor instead.
func (*Calculator_AddRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Calculator_AddRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Calculator_AddRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Calculator_AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculator_AddResponse) Reset() {
	*x = Calculator_AddResponse{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculator_AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculator_AddResponse) ProtoMessage() {}

func (x *Calculator_AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculator_AddResponse.ProtoReflect.Descriptor instead.
func (*Calculator_AddResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Calculator_AddResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type Calculator_SubtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculator_SubtractRequest) Reset() {
	*x = Calculator_SubtractRequest{}
	mi := &file_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculator_SubtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculator_SubtractRequest) ProtoMessage() {}

func (x *Calculator_SubtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculator_SubtractRequest.ProtoReflect.Descriptor instead.
func (*Calculator_SubtractRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *Calculator_SubtractRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Calculator_SubtractRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Calculator_SubtractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Calculator_SubtractResponse) Reset() {
	*x = Calculator_SubtractResponse{}
	mi := &file_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Calculator_SubtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculator_SubtractResponse) ProtoMessage() {}

func (x *Calculator_SubtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculator_SubtractResponse.ProtoReflect.Descriptor instead.
func (*Calculator_SubtractResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *Calculator_SubtractResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\"3\n" +
	"\x15Calculator_AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"0\n" +
	"\x16Calculator_AddResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"8\n" +
	"\x1aCalculator_SubtractRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"5\n" +
	"\x1bCalculator_SubtractResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\xb7\x01\n" +
	"\n" +
	"Calculator\x12L\n" +
	"\x03Add\x12!.calculator.Calculator_AddRequest\x1a\".calculator.Calculator_AddResponse\x12[\n" +
	"\bSubtract\x12&.calculator.Calculator_SubtractRequest\x1a'.calculator.Calculator_SubtractResponseB\x19Z\x17calc/proto;calculatorpbb\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculator_proto_goTypes = []any{
	(*Calculator_AddRequest)(nil),       // 0: calculator.Calculator_AddRequest
	(*Calculator_AddResponse)(nil),      // 1: calculator.Calculator_AddResponse
	(*Calculator_SubtractRequest)(nil),  // 2: calculator.Calculator_SubtractRequest
	(*Calculator_SubtractResponse)(nil), // 3: calculator.Calculator_SubtractResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Add:input_type -> calculator.Calculator_AddRequest
	2, // 1: calculator.Calculator.Subtract:input_type -> calculator.Calculator_SubtractRequest
	1, // 2: calculator.Calculator.Add:output_type -> calculator.Calculator_AddResponse
	3, // 3: calculator.Calculator.Subtract:output_type -> calculator.Calculator_SubtractResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
